### ISSUE TITLE
redirect error ! isRedirect not working

### ISSUE THREAD

**Issue by poweroftrue** [franela/goreq#69]
isRedirect not working maybe it's default settings for go client see: http://golang.org/src/pkg/net/http/client.go

and what about cookies !! 

thanks for cool lib :+1:

**Comment by marcosnils** [comment]
@mostafadahab just wanted to let u know that cookie support has been included in #78 thanks to @bfontaine .

**Comment by mostafadahab** [comment]
good job ! i tried the new  version of goreq but still there issue in redirect with headers and i can't find RedirectHedears ! and the cookie jar not saving set-cookie and resend it in redirect requests

**Comment by marcosnils** [comment]
@mostafadahab can have you updated the library locally?. The RedirectHeaders flag can be set here: 
https://github.com/franela/goreq/blob/master/goreq.go#L38

**Comment by marcosnils** [comment]
@mostafadahab regarding cookies on redirection it hasn't been done because of security concerns. It's not safe to automatically redirect cookies as the final URL might get sensitive cookies information. If you still want do send the cookies anyways, you can redefine the CheckRedirect function here: https://github.com/franela/goreq/blob/master/goreq.go#L276

**Comment by mostafadahab** [comment]
@marcosnils  RedirectHeaders works the problem was not having the last version 

i say the cookie jar must attached for example if i'am make login to facebook.com and facebook redirect to facebook.com/home.php the must have cookies ! if not will log me out !

**Comment by marcosnils** [comment]
@mostafadahab makes sense. We can add a RedirectCookies flag into goreq.Request for that purpose. 
I'll craft a change later today.

**Comment by mostafadahab** [comment]
thanks alot you're awesome

i'm developing me skills in go but it's still weak  

when i'm ready i will try to contribute

**Comment by marcosnils** [comment]
@mostafadahab speaking with @xetorthio I've realized that cookies are currently being forwarded within redirects. Cookies it's just another header in the request, so if you do the following request: 
```go
req := goreq.Request{
        Method:          "GET",
        Uri:             "http://somedomain.com/redirects",
        MaxRedirects:    2,   
        RedirectHeaders: true,
}
req.AddCookie(&http.Cookie{Name: "Test", Value: "Value"})                                                                                                              
res, _ := req.Do()
```

Then the `Cookie` header will be redirected accordingly. 

Per your facebook example seems like you want `goreq` to handle the `set-cookie` header and then send it back to the redirect url specified. That's not something that `goreq` should do because the User-Agent (usually browsers in this case) make a lot of validations when handling cookies which we don't think it's competent to `goreq`. 

What I would recommend you to do is to make the login in two steps

1. Make a request to login (without redirect) and obtain the cookies from the response header (set-cookie)
2. Make further requests using the `goreq` `AddCookie` option and `RedirectHeaders: true`. If a redirect occurs then `goreq` will forward the specified cookie correctly to the destination URL.

**Comment by mostafadahab** [comment]
or just assign global cookiejar to each request

@marcosnils thanks man :+1: :heart_eyes:
