### ISSUE TITLE
Request Body Marshalling and Case Sensitivity

### ISSUE THREAD

**Issue by pmyjavec** [franela/goreq#91]
When marshalling structs to JSON for use in the request body case sensitivity can be an issue. Currently the field names are sent, in JSON using upper case:

```
{"Name":"Test","Key":"TST"}
```

The issue is that according to the JSON RPC specification parameter names are case sensitive. See http://jsonrpc.org/historical/json-rpc-1-1-alt.html#service-procedure-and-parameter-names for information

I believe in the majority of cases parameter names are lower case, so I think a conversion helper is required

**Comment by pmyjavec** [comment]
Sorry, this is more because I am a Golang n00b and forgot about using tags. The issue is easily overcome by defining my struct like so:

```
type NewStashProject struct {
    Name string `json:"name"`
    Key  string `json:"key"`
}
```

If you guys think it's work it I can update the README?

**Comment by marcosnils** [comment]
@pmyjavec It's well known that you should use tags to specify attribute names when marshaling json in Go. I don't believe updating the README is necessary to reflect this. 

If it comes a common issue we'll surely do it.
Thx!.

**Comment by sschepens** [comment]
I had the same thing asked last week, for newcommers it's confusing, because Upper Case fields get marshalled properly, so one would think that using lower case fields would the inverse effect.
But field's don't even get marshalled because golang's marshalling relies on runtime reflection and lower case fields are private...
I don't know if adding this to the issue would help, but maybe I would add a comment and a link to somewhere with golang and json documentation, suggesting to read it if newbie.

Cheers!

**Comment by pmyjavec** [comment]
@sschepens yes that is what was confusing to me at first. It is counter intuitive at first.

@marcosnils is right, people know about tags or should know about them. If not this issue will probably help out :)
